opapi/src/generators/errors.ts
Closes CLS-697
Adding the `isApiError=true` field ensures the `isApiError()` check can succeed for `BaseApiError` instances that were created outside of the current generated code.
For example, we have a `Server` class that uses receives an error from a 3rd party library called `Client`. The `Server` receives an error `e`, which he wants to pass to `isApiError(e)`. Since the `Server` uses his own opapi-generated `isApiError()` function, the `isApiError(e)` will always fail since the `BaseApiError` used by `Server` is not necessarily the same `BaseApiError` class used by the 3rd party `Client`.
Adding the `isApiError=true` field solves this problem.
=> feat(opapi): add isApiError field to errors

opapi/package.json, opapi/src/generator.ts, opapi/src/section-types-generator/generator.ts, opapi/src/section-types-generator/helpers.ts, opapi/src/section-types-generator/parsers.ts, opapi/src/section-types-generator/types.ts, opapi/test/api.ts
- properties with existing block names are parsed as dependencies
=> fix(opapi): - properties with similar names are incorrectly parsed

opapi/package.json, opapi/src/opapi.ts, opapi/src/state.ts, opapi/src/util.ts
This will allow doing:
```ts
import { OpenApi } from '@bpinternal/opapi'
import { api } from '@botpress/api'
const { errors } = api.getState()
const chatApi = OpenApi({
metadata: {
description: '...',
server: 'http://localhost:3000',
title: '...',
version: '0.0.0',
},
errors // simply reuse errors from the Botpress API
})
```
instead of:
```ts
// gen.ts
import { api } from '@botpress/api'
api.exportState("./gen")
// index.ts
import { state } from './gen'
const chatApi = OpenApi({
metadata: {
description: '...',
server: 'http://localhost:3000',
title: '...',
version: '0.0.0',
},
errors: state.errors
})
```
=> feat(opapi): allow getting state without exporting it

jex/package.json, jex/src/index.ts, jex/src/jex-representation/jex-extends.test.ts, jex/src/jex-representation/jex-extends.ts, jex/src/jex-representation/property-path.test.ts, jex/src/jex-representation/property-path.ts, jex/src/jex-representation/to-string.test.ts, jex/src/jex-representation/to-string.ts, jex/src/utils/type-utils.ts
Example 1:
```
undefined ⊆ number ?
- #: undefined ⊈ number
{a: string | undefined} ⊆ {a: string} ?
- #.a: undefined ⊈ string
string | number | undefined | null ⊆ string | number ?
- #: undefined ⊈ string
- #: undefined ⊈ number
- #: null ⊈ string
- #: null ⊈ number
string ⊆ "banana" ?
- #: string ⊈ "banana"
"banana" ⊆ number | "apple" ?
- #: "banana" ⊈ number
- #: "banana" ⊈ "apple"
string[] ⊆ number[] ?
- #[number]: string ⊈ number
[string, number] ⊆ number[] ?
- #[0]: string ⊈ number
Record<string, string | undefined | boolean> ⊆ Record<string, string> ?
- #[string]: undefined ⊈ string
- #[string]: boolean ⊈ string
```
Example 2:
```ts
import zodToJsonSchema from 'zod-to-json-schema'
import * as z from 'zod'
import * as jex from './src'
import { JSONSchema7 } from 'json-schema'
const …
```
=> feat(jex): extension check returns a reason on failure

zui/package.json, zui/src/index.ts, zui/src/ui/index.tsx, zui/src/ui/types.ts, zui/tsup.config.ts
- Add missing type export of `ZuiReactComponent` for specifying custom components
- Improved typing of input schema 
- Fixed React typings
- Handled empty or undefined schema rendering
=> chore(zui): Version 0.2.3

zui/package.json, zui/src/ui/index.tsx, zui/src/ui/types.ts
the `context` parameter now has access to the following:
- formData: the full form's current values
- formErrors: the full form's array of validation errors
- readonly: whether the whole form is set to readonly, defaults to false if undefined
- dispatch: The underlying dispatch function for JSON Form's state reducer
Remove access to cells and renderers as it is a JSON Form construct we are not using
=> feat(zui): Give access to full form state in component context params

opapi/package.json, opapi/pnpm-lock.yaml, opapi/src/handler-generator/export-schemas.ts, opapi/src/handler-generator/index.ts, opapi/src/jsonschema.test.ts, opapi/src/jsonschema.ts, opapi/src/opapi.ts, opapi/test/export-schemas.test.ts
This is some logic I have copied in webchat-api, chat-api and now hitl-api. It allows exporting any kind of schemas (even schemas that arent requests or responses) to fully separate build time from runtime
=> feat(opapi): allow exporting arbitrary schemas

zui/package.json, zui/src/index.ts, zui/src/ui/Form.tsx, zui/src/ui/component-definitions.ts, zui/src/ui/index.ts, zui/src/ui/types.ts, zui/src/ui/ui.test.tsx, zui/src/z/types/basetype/index.ts, zui/src/z/types/error/index.ts, zui/src/z/types/error/locales/en.ts
This was not the original design, but it will simplify the DX.
=> chore(zui): move studio component definitions in zui as defaults

zui/src/transforms/zui-to-typescript-next/index.test.ts, zui/src/transforms/zui-to-typescript-next/index.ts, zui/src/transforms/zui-to-typescript-next/utils.test.ts, zui/src/transforms/zui-to-typescript-next/utils.ts
This PR does 3 things:
1. replace all function declarations by arrow functions declaration, for simplicity:
```ts
// before
declare function add(x: number, y: number): number
// after
declare const add: (x: number, y: number) => number
```
2. allow declaring type instead of variable:
```ts
// with { declaration: true } or { declaration: "variable" }
declare const add: (x: number, y: number) => number
// with { declaration: "type" }
type add = (x: number, y: number) => number
```
3. allow generating a generic type from a zui ref
```ts
const schema = z.object({ foo: z.ref("T") }).title("X")
type X<T> = { foo: T }
```
=> feat(zui): convert references to type arguments

zui/src/index.ts, zui/src/transforms/common/errors.ts, zui/src/transforms/common/eval-zui-string.ts, zui/src/transforms/json-schema-to-zui/index.ts, zui/src/transforms/object-to-zui/index.ts, zui/src/transforms/zui-to-json-schema/parseDef.ts, zui/src/transforms/zui-to-typescript-schema/index.test.ts, zui/src/transforms/zui-to-typescript-schema/index.ts, zui/src/transforms/zui-to-typescript-type/index.test.ts, zui/src/transforms/zui-to-typescript-type/index.ts
all thrown errors in any transformed function is properly typed and exported
=> chore(zui): standardize the way transforms throw errors

jex/src/builders/jexir-builder.ts, jex/src/builders/json-schema-builder.ts, jex/src/jex-extends.test.ts, jex/src/jex-extends.ts, jex/src/jexir/from-json-schema.test.ts, jex/src/jexir/from-json-schema.ts, jex/src/jexir/to-json-schema.test.ts, jex/src/jexir/to-string.test.ts, jex/src/jexir/to-string.ts, jex/src/jexir/typings.ts
In typescript,`any` is equivalent to a `// @ts-ignore` indicator. It tells typescript not to check the type.
In JSON Schema, `any` does not exist. An empty schema means a schema with no constraints or in other words, any kind of data. An empty schema should thus be treated like unknown; i.e. the most global type. 
This way, `unknown ⊈ string`, but `string ⊆ unknown`
=> feat(jex): replace any by unknown

const/index.code-workspace, depsynky/index.code-workspace, entities/index.code-workspace, es-node/index.code-workspace, expresso/index.code-workspace, genenv/index.code-workspace, jex/index.code-workspace, log4bot/index.code-workspace, opapi/index.code-workspace, promex/index.code-workspace, ptb-schema/index.code-workspace, readiness/index.code-workspace, trail/index.code-workspace, tunnel/index.code-workspace, verel/index.code-workspace, yargs-extra/index.code-workspace, zui/index.code-workspace
In each and every package, there is a `index.code-workspace` file that you can open. Doing so will only open the desired package in vscode. You can then have different vscode settings for each packages without messing up the git tab
=> chore: standardize code workspaces in packages

verel/package.json, verel/pnpm-lock.yaml
Browser tests keep failing with error:
```
WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 8MB. Use WebAssembly.compile, compile on a worker thread, or use the flag `--enable-features=WebAssemblyUnlimitedSyncCompilation`.
```
I have little time to dig deeper into that + we don't currently use verel in the browser because its too big anyway
=> chore(verel): disable browser tests

zui/src/setup.test.ts, zui/src/transforms/common/utils.test.ts, zui/src/transforms/zui-to-typescript-type/index.test.ts, zui/src/transforms/zui-to-typescript-type/index.ts, zui/src/transforms/zui-to-typescript-type/primitives.test.ts, zui/src/vitest.d.ts
The custom vitest expect `toBeValidTypescript` below
```ts
expect(`const a: string = "banana"`).toBeValidTypescript()
```
was unbelievably slow. 
By migrating to proper tests with clear expected values, the test execution time goes down by a factor of more than 10x (~140s to ~10s)
=> chore(zui): drastically improve zui test speed by removing toBeValidTypescript custom expect

opapi/package.json, opapi/src/generators/errors.ts, opapi/src/state.ts
There was a separate place where the new HTTP code had to be also added. I also added a type guard to prevent this from being overlooked so easily in the future.
=> fix(opapi): include HTTP 424 in ApiError.status and add type guard

zui/package.json, zui/src/ui/index.ts, zui/src/ui/utils.ts
The lib only exports JSONSchema, but in 90% of our use cases, we use the ObjectSchema only. This would just expose the types that are under JSONSchema, and a small guard to simplify usage
=> fix(zui): export schemas of JSONSchema

zui/package.json, zui/src/ui/ui.test.tsx
In vitest 1.x, the `callls` member of the `MockContext` interface is defined as `TArgs[]`, with `TArgs` being provided by `const mock = vi.fn<TArgs, TRet>()`. However, if we do not provide type parameters to `vi.fn`, `TArgs` will default to `any`, which means we'd have `interface MockContext { calls: any[] }`, but the actual real type is `any[][]`, since `calls` is an array of arrays of invocation parameters.
In vitest 2.x, the signature of `vi.fn` was changed to `vi.fn<TFunc = any>` and `MockContext` was updated to `interface MockContext { calls: Parameters<TFunc> }`. This means that even if we omit providing a type to `vi.fn()`, `calls` will properly have the type `any[][]` instead of the `any[]` from vitest 1.x.
This means that in vitest 1.x, if you were to do something like `const spy …
=> fix(zui): fix ui test "calls onValidation w/ validation"

zui/package.json, zui/src/transforms/zui-to-typescript-schema/index.ts
- `z.array` now correctly appends description and extensions
- the multi-line comments are removed, since they're redundant now that everything has a `.describe`
=> fix(zui): fix comments, extensions in toTypescriptSchema

zui/package.json, zui/src/transforms/common/json-schema.ts, zui/src/transforms/zui-to-typescript-schema/array-checks.ts, zui/src/transforms/zui-to-typescript-schema/bigint-checks.ts, zui/src/transforms/zui-to-typescript-schema/date-checks.ts, zui/src/transforms/zui-to-typescript-schema/index.test.ts, zui/src/transforms/zui-to-typescript-schema/index.ts, zui/src/transforms/zui-to-typescript-schema/number-checks.ts, zui/src/transforms/zui-to-typescript-schema/set-checks.ts, zui/src/transforms/zui-to-typescript-schema/string-checks.ts
Adresses CLS-2681
```ts
const mySchema = z.string().min(1)
const generated = mySchema.toTypescriptSchema()
console.log(generated) // "z.string().min(1)"
```
=> fix(zui): toTypescriptSchema transform supports checks for most types like string and number

zui/package.json, zui/src/transforms/zui-to-json-schema/parsers/object.ts, zui/src/z/types/discriminatedUnion/index.ts, zui/src/z/types/object/index.ts, zui/src/z/types/object/object.test.ts, zui/src/z/types/utils/partialUtil.ts
In a Zod object, `catchall` and `unknownKeys` should be mutually exclusive. Allowing both leads to inconsistent and unintuitive behavior:
```ts
const schema1 = z.object({ foo: z.string() }).passthrough().catchall(z.string())
const schema2 = z.object({ foo: z.string() }).passthrough().catchall(z.never())
console.log(schema1.safeParse({ foo: 'bar', baz: 42 }).success) // false
console.log(schema2.safeParse({ foo: 'bar', baz: 42 }).success) // true
```
This is confusing—especially because `.passthrough()` implies all unknown keys are allowed, while `.catchall(z.never())` explicitly disallows them.
The first attempted solution involved modeling all behaviors around additional properties using two separate keys: `strip: boolean` and `catchall: ZodTypeAny`.
```ts
export interface ZodObjectDef<T …
```
=> fix(zui): consistent catchall and extra keys behavior

zui/src/z/clone.test.ts, zui/src/z/types/array/index.ts, zui/src/z/types/basetype/index.ts, zui/src/z/types/branded/index.ts, zui/src/z/types/catch/index.ts, zui/src/z/types/default/index.ts, zui/src/z/types/discriminatedUnion/index.ts, zui/src/z/types/function/index.ts, zui/src/z/types/intersection/index.ts, zui/src/z/types/lazy/index.ts, zui/src/z/types/map/index.ts, zui/src/z/types/nullable/index.ts, zui/src/z/types/object/index.ts, zui/src/z/types/optional/index.ts, zui/src/z/types/pipeline/index.ts, zui/src/z/types/promise/index.ts, zui/src/z/types/readonly/index.ts, zui/src/z/types/record/index.ts, zui/src/z/types/set/index.ts, zui/src/z/types/transformer/index.ts, zui/src/z/types/tuple/index.ts, zui/src/z/types/union/index.ts
All metadata modifiers, like `.title()`, `.disabled()`, `.displayAs()`, `.placeholder()`, and eventually `.describe()`, update the metadata root in place and then return a self-reference. To prevent surprises, it would be safer to return a deep clone of the schema.
This PR offers a way to clone a schema recursively using `schema.clone()`. It is not yet used internally.
=> feat(zui): allow deep cloning a zui schema

zui/src/transforms/zui-to-json-schema-next/index.test.ts, zui/src/transforms/zui-to-json-schema/test/meta.test.ts, zui/src/transforms/zui-to-typescript-type/index.test.ts, zui/src/transforms/zui-to-typescript-type/index.ts, zui/src/z/types/basetype/index.ts
Just like for titles and other schema metadata, when using a construction like:
```ts
const mySchema = z.object({
foo: z.string().optional().default("foo").describe("Foo")
})
```
we want the description to apply to the string, not the default or the optional. The result should look like:
```ts
{
type: 'object',
properties: {
foo: {
type: 'string',
description: 'Foo',
default: 'foo'
}
},
required: [],
}
```
=> chore(zui): description is applied on metadata root

zui/package.json, zui/src/transforms/common/json-schema.ts, zui/src/transforms/json-schema-to-zui-next/guards.ts, zui/src/transforms/json-schema-to-zui-next/index.test.ts, zui/src/transforms/json-schema-to-zui-next/index.ts, zui/src/transforms/transform-pipeline.test.ts, zui/src/transforms/zui-to-json-schema-next/index.test.ts, zui/src/transforms/zui-to-json-schema-next/index.ts
I don't care about preserving the `z.discriminatedUnion()` when mapping to and from JSON Schema. There's no use case for it; both union and discriminated union have the exact same meaning. I prefer having a simpler logic.
=> chore(zui): rm the special lossless discriminated union json-schema transform

zui/package.json, zui/src/z/types/object/index.ts, zui/src/z/types/object/object.test.ts, zui/src/z/utils.ts
The problem with merging catchall types:
```ts
{
[K: string]: CatchType
}
```
Is that this type swallows the object type, so all keys must be `CatchType`.
This is not a perfect solution, but I couldn't find better. "catch all" types are now unknown, but original types of known keys are preserved.
=> fix(zui): catchall inference

zui/src/index.ts, zui/src/transforms/json-schema-to-zui-next/index.ts, zui/src/transforms/json-schema-to-zui/index.ts, zui/src/transforms/json-schema-to-zui/json-schema-to-zui.test.ts, zui/src/transforms/json-schema-to-zui/parsers/parseObject.test.ts, zui/src/transforms/json-schema-to-zui/parsers/parseString.test.ts, zui/src/transforms/object-to-zui/index.ts, zui/src/transforms/object-to-zui/object-to-zui.test.ts, zui/src/transforms/zui-to-json-schema-next/index.ts, zui/src/transforms/zui-to-json-schema/zui-extension.test.ts, zui/src/transforms/zui-to-json-schema/zui-extension.ts, zui/src/transforms/zui-to-typescript-type/index.test.ts, zui/src/transforms/zui-to-typescript-type/index.ts, zui/src/transforms/zui-to-typescript-type/primitives.test.ts, zui/src/z/types/basetype/index.ts, zui/src/z/types/index.ts, zui/src/z/z.ts
Previous `fromJsonSchema` and `toJsonSchema` transformers are now named with suffix legacy. What was previously prefixed with `experimental` is now the default behavior.
=> feat(zui): rename transformers

zui/src/index.ts, zui/src/transforms/common/errors.ts, zui/src/transforms/common/json-schema.ts, zui/src/transforms/index.ts, zui/src/transforms/json-schema-to-zui-next/index.test.ts, zui/src/transforms/json-schema-to-zui-next/index.ts, zui/src/transforms/json-schema-to-zui/index.ts, zui/src/transforms/json-schema-to-zui/json-schema-to-zui.test.ts, zui/src/transforms/object-to-zui/object-to-zui.test.ts, zui/src/transforms/transform-pipeline.test.ts, zui/src/transforms/zui-to-json-schema-next/index.test.ts, zui/src/transforms/zui-to-json-schema-next/index.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/array.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/set.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/string.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/tuple.ts, zui/src/transforms/zui-to-json-schema/index.ts, zui/src/transforms/zui-to-json-schema/zui-extension.test.ts, zui/src/transforms/zui-to-json-schema/zui-extension.ts, zui/src/z/types/basetype/index.ts
I renamed most occurrences of `Json` to `JSON` so the casing can be the exact same as zod v4: https://zod.dev/v4?id=json-schema-conversion
=> chore(zui): move some functions around + use same casing as zod v4
