botpress/packages

expresso/CHANGELOG.md, expresso/jest.config.js, expresso/package.json, expresso/src/openapi.ts, expresso/src/router.test.ts, expresso/src/router.ts, expresso/src/typings.ts, expresso/yarn.lock
Adds support so we can easily add additional middlewares seamlessly
=> feat(expresso): add support for multiple handlers/mw

yargs-extra/readme.md
=> docs: fix typo

yargs-extra/.npmignore, yargs-extra/package.json, yargs-extra/src/parse-env.test.ts, yargs-extra/src/parse-value.ts, yargs-extra/yarn.lock
there's no CI, but trust me, it passes
=> feat(yargs-extra): allow passing array options as environement variables

opapi/package.json, opapi/src/opapi.ts, opapi/src/state.ts
added back default parameters not to break everything
this is already published on npm
=> fix(openapi): add default type arguments for ease of use

opapi/package.json, readiness/bin.js, readiness/package.json, readiness/pnpm-lock.yaml, readiness/readme.md, readiness/src/check.ts, readiness/src/config.ts, readiness/src/index.ts, readiness/src/server.ts, readiness/tsconfig.json
diff from original code:
- I removed vite and hot reloading
- I changed usage of logger from `@botpress/common` to `@bpinternal/log4bot`
=> feat(readiness): new package to add a readiness probe on databases and services

trail/src/trace.ts
Formatted code according to `.prettierrc`
=> chore(trail): format code

trail/package.json, trail/yarn.lock
Using the latest `@prisma/instrumentation` requires updating some deps
Closes CLS-830
=> chore(trail): upgrade otel deps

tunnel/e2e/browser/index.ts, tunnel/e2e/browser/ts-script.ts, tunnel/e2e/index.ts, tunnel/e2e/nodejs.ts, tunnel/package.json, tunnel/src/tunnel-client.ts, tunnel/src/types.ts
This feature is not a ping-pong mechanism. The goal is not for the server to send ping's and expect client to answer with pongs to see if its still availble. 
The goal is simply to allow the client to say hello from time to time to keep the connection alive
release plan:
1. update tunnel lib version in the tunnel server in repo skynet
2. deploy the new tunnel server (this is backward compatible with current CLI)
3. update tunnel lib version in the CLI in repo botpress
4. release new CLI
=> feat(tunnel): added hello feature to keep connection alive

const/package.json, const/src/limits.ts
=> feat(const): add issue_event_item_payload_bytes

const/package.json, const/src/quotas.ts
=> feat(const): token spend quota

const/src/quotas.ts
=> fix(const): adjusted quotas

opapi/package.json, opapi/src/generators/handlers.ts, opapi/src/openapi.ts, opapi/src/state.ts, opapi/test/api.ts
Didnt know, but its already supported in openapi :D
=> feat(opapi): support boolean parameters

zui/package.json, zui/pnpm-lock.yaml, zui/src/index.ts, zui/src/zui-to-json-schema.ts
=> fix(zui): fix type import from zod-to-json

zui/package.json, zui/src/object-to-zui.test.ts, zui/src/object-to-zui.ts, zui/src/zui.ts
- Choose optional/nullable when creating from an object
- Fix array typings
- Add options to .toJsonSchema/fromObject
=> fix(zui): use options & add config & fix array

zui/package.json, zui/src/zui-to-json-schema.test.ts, zui/src/zui-to-json-schema.ts, zui/src/zui.test.ts, zui/src/zui.ts
add zui.lazy, and fix the generated json schema
=> feat(zui): support lazy

.github/workflows/trail.yml, renovate.json, trail/package.json, trail/pnpm-lock.yaml, trail/src/index.ts, trail/src/trace.ts, trail/tests/disabled.test.ts, trail/tests/enabled.test.ts, trail/tests/init.test.ts, trail/vite.config.ts
`yn` is an esm module and importing trail w/ `node -r @bpinternal/trail/init` is using a `require` call. So the `esm` module would break the `require` call.
=> chore(trail): removed unwanted dependency yn

jex/src/index.ts, jex/src/jex-representation/from-jex.test.ts, jex/src/jex-representation/to-jex.test.ts, jex/src/jex-representation/to-jex.ts
This reverts commit c062e935be2b6756aa4df184bcbf695d03b6aeb1.
=> chore(jex): revert sync version of every jex function (#127)

zui/package.json, zui/pnpm-lock.yaml
Removes the cli-related stuff so it doesn't require anything related to FS
=> chore(deps): update json-schema-to-zod to remove fs depenency

opapi/package.json, opapi/src/generators/handlers.ts, opapi/src/openapi.ts, opapi/src/state.ts, opapi/test/api.ts
=> feat(opapi): support numeric request params

zui/package.json, zui/src/transforms/json-schema-to-zui/index.ts, zui/src/transforms/object-to-zui/object-to-zui.test.ts, zui/src/transforms/zui-to-json-schema/zui-extension.ts, zui/src/ui/index.tsx, zui/src/ui/providers/FormDataProvider.tsx, zui/src/ui/stories/ZuiForm.stories.tsx, zui/src/ui/types.ts, zui/src/ui/ui.test.tsx, zui/src/z/types/default/index.ts, zui/src/z/types/discriminatedUnion/index.ts, zui/src/z/types/string/index.ts
- Fixes handling of tuples by serializers and deserializers
- added an export for the `emojiRegex` used to implement emoji pickers
=> fix(zui): Fix tuples and add export for emoji picker implementations

zui/package.json, zui/src/transforms/zui-to-json-schema/zui-extension.ts
- Fixes `z.map()` types in serialization
=> fix(zui): Fix Map in serializer

zui/package.json
=> chore(zui): use pnpm 9.1.0

zui/package.json, zui/src/z/extensions.ts, zui/src/z/z.ts, zui/src/zui.test.ts
=> feat(zui): Custom types, botpress specific

zui/package.json, zui/src/z/z.ts
Bad export ordering causing random circular dependency errors
=> fix(zui): Fix import ordering

zui/package.json, zui/src/z/extensions.ts
- Adds `z.knowledgebase` custom type
=> feat(zui): Add knowledgebase custom type

renovate.json
I don't know if this will fix the issue, but its worth a try
=> chore: tag pnpm version in renovate file

zui/package.json, zui/src/transforms/json-schema-to-zui/index.ts, zui/src/ui/types.ts, zui/src/z/types/basetype/index.ts, zui/src/z/types/string/index.ts
adds `.secret()` support for strings containing passwords
=> feat(zui): add .secret() to strings

zui/package.json, zui/src/z/types/basetype/index.ts
- type change did not get commited for some reason
=> fix(zui): Fix typing of toTypescript options

zui/README.md, zui/package.json, zui/src/index.ts, zui/src/ui/Form.tsx, zui/src/ui/hooks/useFormData.tsx, zui/src/ui/types.ts, zui/src/ui/ui.test.tsx
Allows you to receive the validation data outside the form
=> feat(zui): Add onValidation callback to Form props

opapi/package.json, opapi/src/handler-generator/export-handler.ts
All we see currently is "Request failed with status code 500" which is pretty much useless...
=> fix(opapi): get real error message

zui/package.json, zui/playground.ts
I don't believe this is still used
=> chore(zui): rm playground and storybook

.github/workflows/genenv.yml, genenv/bin.js, genenv/build.ts, genenv/package.json, genenv/pnpm-lock.yaml, genenv/readme.md, genenv/src/config.ts, genenv/src/consts.ts, genenv/src/generate.test.ts, genenv/src/generate.ts, genenv/src/index.ts, genenv/tsconfig.json
Program:
```bash
export MY_ENV1=foo
export MY_ENV2=bar
npx genenv gen -o ./.secrets/index.ts -e MY_ENV1 -e MY_ENV2 -e MY_ENV3
cat ./.secrets/index.ts
```
Output:
```typescript
export const MY_ENV1 = 'foo'
export const MY_ENV2 = 'bar'
export const MY_ENV3 = '$MY_ENV3' // default value
=> feat(genenv): Small CLI to generate typescript file exporting constants from environment variables

const/package.json, const/src/quotas.ts
=> chore(quotas): add V3 quotas

renovate.json
=> chore: renovate update packages once a month

opapi/package.json, opapi/src/generators/client-node.ts
=> fix(opapi): ensure we never send a body with GET requests

const/package.json, const/src/prefixes.ts
=> feat(const): add id prefix for plugin versions

opapi/package.json, opapi/src/generators/types.ts, opapi/test/server.test.ts, opapi/test/util.ts
=> fix(opapi): post request with empty body results in operation input being Record<string, never>

zui/package.json, zui/src/z/types/utils/custom-set.test.ts, zui/src/z/types/utils/custom-set.ts, zui/src/z/types/utils/is-equal.test.ts, zui/src/z/types/utils/is-equal.ts
same as lodash's isEqual, but does not consider undefined object values
=> feat: add custom isEqual comparer

zui/package.json, zui/src/transforms/common/errors.ts, zui/src/transforms/common/json-schema.ts, zui/src/transforms/json-schema-to-zui-next/index.ts, zui/src/transforms/json-schema-to-zui-next/primitives/index.ts, zui/src/transforms/json-schema-to-zui-next/primitives/string.ts, zui/src/transforms/transform-pipeline.test.ts, zui/src/transforms/zui-to-json-schema-next/index.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/string.ts, zui/src/z/types/string/datetime.test.ts, zui/src/z/types/string/datetime.ts, zui/src/z/types/string/index.ts, zui/src/z/types/string/string.test.ts
=> feat(transformers/json next): preserve string checks

zui/package.json, zui/src/transforms/common/json-schema.ts, zui/src/transforms/json-schema-to-zui-next/index.test.ts, zui/src/transforms/json-schema-to-zui-next/index.ts, zui/src/transforms/json-schema-to-zui-next/iterables/array.ts, zui/src/transforms/zui-to-json-schema-next/index.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/array.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/set.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/tuple.ts
=> feat(zui/json next): add support for array/set checks

thicktoken/package.json, thicktoken/pnpm-lock.yaml, thicktoken/tsconfig.json, thicktoken/tsup.config.ts
trying to fix typing issue related to the use of src instead of dist typings
=> fix(thicktoken): fix types

zui/package.json, zui/src/transforms/common/json-schema.ts, zui/src/transforms/zui-to-json-schema-next/index.test.ts, zui/src/transforms/zui-to-json-schema-next/index.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/array.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/number.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/set.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/string.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/tuple.ts, zui/src/z/types/basetype/index.ts
We're getting close to the last steps before officially making a switch of json-schema transform logic
=> fix(zui): keep descriptions when mapping zod to json-schema

zui/package.json, zui/src/transforms/common/index.ts, zui/src/transforms/common/regex-utils/escape-special-chars.test.ts, zui/src/transforms/common/regex-utils/escape-special-chars.ts, zui/src/transforms/common/regex-utils/index.ts, zui/src/transforms/zui-to-json-schema-next/type-processors/string.ts, zui/src/transforms/zui-to-json-schema/parsers/string.ts
=> fix(transformers): do not generate invalid regexes

.github/workflows/retry.yml, retry/bin.js, retry/index.code-workspace, retry/package.json, retry/pnpm-lock.yaml, retry/readme.md, retry/src/index.ts, retry/src/parse-argv.ts, retry/src/retry-cli.test.ts, retry/tsconfig.json
The lib is not maintained and currently fails in the botpress/botpress CI.
=> feat(retry-cli): new package forked from tirsen/retry-cli

zui/package.json, zui/src/transforms/common/utils.test.ts, zui/src/transforms/common/utils.ts, zui/src/transforms/zui-to-typescript-type/index.test.ts, zui/src/transforms/zui-to-typescript-type/index.ts
Bring some fixes from https://github.com/botpress/botpress/blob/master/packages/llmz/src/typings.ts
closes https://linear.app/botpress/issue/STU-1165/update-zui-to-implement-typing-fixes-from-llmz
=> fix(zui): fix typings from llmz
